export const hitterStats = [
    {
        firstName: 'Aaron',
        lastName: 'Judge',
        team: 'NYY',
        pos: 'RF',
        avg: .360,
        h: 121,
        bb: 65,
        hr: 34,
        rbi: 75,
        g: 91,
        ab: 336,
        obp: .467,
        slg: .738,
        ops: 1.205,
    },
    {
        firstName: 'Mike',
        lastName: 'Trout',
        team: 'LAA',
        pos: 'CF',
        avg: .233,
        h: 52,
        bb: 42,
        hr: 14,
        rbi: 33,
        g: 64,
        ab: 223,
        obp: .408,
        slg: .576,
        ops: .984,
    },
    {
        firstName: 'Ronald',
        lastName: 'Acuña Jr.',
        team: 'ATL',
        pos: 'LF',
        avg: .331,
        h: 34,
        bb: 30,
        hr: 9,
        rbi: 18,
        g: 40,
        ab: 139,
        obp: .450,
        slg: .561,
        ops: 1.011,
    },
    {
        firstName: 'Shohei',
        lastName: 'Ohtani',
        team: 'LAD',
        pos: 'DH',
        avg: .281,
        h: 100,
        bb: 57,
        hr: 31,
        rbi: 57,
        g: 91,
        ab: 356,
        obp: .383,
        slg: .615,
        ops: .998,
    },
    {
        firstName: 'Bryce',
        lastName: 'Harper',
        team: 'PHI',
        pos: '1B',
        avg: .249,
        h: 59,
        bb: 40,
        hr: 9,
        rbi: 34,
        g: 64,
        ab: 237,
        obp: .364,
        slg: .418,
        ops: .782,
    },
    {
        firstName: 'Ketel',
        lastName: 'Marte',
        team: 'AZ',
        pos: '2B',
        avg: .291,
        h: 68,
        bb: 38,
        hr: 19,
        rbi: 40,
        g: 64,
        ab: 234,
        obp: .397,
        slg: .581,
        ops: .978,
    },
    {
        firstName: 'Jacob',
        lastName: 'Wilson',
        team: 'ATH',
        pos: 'SS',
        avg: .335,
        h: 111,
        bb: 20,
        hr: 9,
        rbi: 42,
        g: 85,
        ab: 331,
        obp: .379,
        slg: .468,
        ops: .847,
    },
    {
        firstName: 'Jose',
        lastName: 'Ramirez',
        team: 'CLE',
        pos: '3B',
        avg: .299,
        h: 98,
        bb: 32,
        hr: 16,
        rbi: 44,
        g: 87,
        ab: 328,
        obp: .364,
        slg: .503,
        ops: .867,
    },
    {
        firstName: 'Cal',
        lastName: 'Raleigh',
        team: 'SEA',
        pos: 'C',
        avg: .268,
        h: 88,
        bb: 57,
        hr: 36,
        rbi: 76,
        g: 89,
        ab: 328,
        obp: .383,
        slg: .646,
        ops: 1.029,
    },
    {
        firstName: 'Riley',
        lastName: 'Greene',
        team: 'DET',
        pos: 'LF',
        avg: .282,
        h: 99,
        bb: 27,
        hr: 22,
        rbi: 72,
        g: 91,
        ab: 351,
        obp: .336,
        slg: .530,
        ops: .866,
    },
    {
        firstName: 'Jonathan',
        lastName: 'Aranda',
        team: 'TB',
        pos: '1B',
        avg: .321,
        h: 96,
        bb: 32,
        hr: 11,
        rbi: 49,
        g: 87,
        ab: 299,
        obp: .397,
        slg: .492,
        ops: .889,
    },
    {
        firstName: 'Will',
        lastName: 'Smith',
        team: 'LAD',
        pos: 'C',
        avg: .332,
        h: 78,
        bb: 43,
        hr: 12,
        rbi: 45,
        g: 71,
        ab: 235,
        obp: .434,
        slg: .557,
        ops: .991,
    },
]