export const pitcherStats = [
    {
        firstName: 'Clay',
        lastName: 'Holmes',
        team: 'NYM',
        w: 8,
        l: 4,
        s: 0,
        era: 2.99,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Brandon',
        lastName: 'Young',
        team: 'BAL',
        w: 0,
        l: 3,
        s: 4,
        era: 7.02,
        g: 4,
        gs: 4,
        ip: 16.2,
        h: 22,
        r: 13,
        er: 13,
        hr: 2,
        bb: 11,
        so: 15,
        avg: .328,
        whip: 1.98,
    },
    {
        firstName: 'Ryan',
        lastName: 'Pepiot',
        team: 'TB',
        w: 6,
        l: 6,
        s: 0,
        era: 3.34,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },    
    {
        firstName: 'Jack',
        lastName: 'Flaherty',
        team: 'DET',
        w: 5,
        l: 9,
        s: 0,
        era: 4.84,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Logan',
        lastName: 'Gilbert',
        team: 'SEA',
        w: 2,
        l: 2,
        s: 3.40,
        era: 3.43,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Will',
        lastName: 'Warren',
        team: 'NYY',
        w: 5,
        l: 4,
        s: 0,
        era: 5.02,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Kyle',
        lastName: 'Freeland',
        team: 'COL',
        w: 1,
        l: 9,
        s: 0,
        era: 5.49,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Brayan',
        lastName: 'Bello',
        team: 'BOS',
        w: 4,
        l: 2,
        s: 0,
        era: 3.42,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Eury',
        lastName: 'Pérez',
        team: 'MIA',
        w: 1,
        l: 2,
        s: 0,
        era: 4.50,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Nick',
        lastName: 'Martinez',
        team: 'CIN',
        w: 6,
        l: 8,
        s: 0,
        era: 4.20,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Mitch',
        lastName: 'Keller',
        team: 'PIT',
        w: 3,
        l: 10,
        s: 0,
        era: 3.64,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Seth',
        lastName: 'Lugo',
        team: 'KC',
        w: 6,
        l: 5,
        s: 0,
        era: 2.65,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Shota',
        lastName: 'Imanaga',
        team: 'CHC',
        w: 5,
        l: 2,
        s: 0,
        era: 2.78,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Simeon',
        lastName: 'Woods Richardson',
        team: 'MIN',
        w: 4,
        l: 4,
        s: 0,
        era: 4.41,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Chris',
        lastName: 'Bassit',
        team: 'TOR',
        w: 8,
        l: 4,
        s: 0,
        era: 4.32,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Aaron',
        lastName: 'Civale',
        team: 'CWS',
        w: 1,
        l: 5,
        s: 0,
        era: 4.60,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Clayton',
        lastName: 'Kershaw',
        team: 'LAD',
        w: 4,
        l: 0,
        s: 0,
        era: 3.43,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Jacob',
        lastName: 'Misiorowski',
        team: 'MIL',
        w: 3,
        l: 1,
        s: 0,
        era: 3.20,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Jake',
        lastName: 'Irvin',
        team: 'WSH',
        w: 7,
        l: 3,
        s: 0,
        era: 4.71,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Andre',
        lastName: 'Pallante',
        team: 'STL',
        w: 5,
        l: 4,
        s: 0,
        era: 4.10,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Joey',
        lastName: 'Cantillo',
        team: 'CLE',
        w: 1,
        l: 0,
        s: 0,
        era: 3.41,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Hunter',
        lastName: 'Brown',
        team: 'HOU',
        w: 9,
        l: 3,
        s: 0,
        era: 1.82,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Nathan',
        lastName: 'Eovaldi',
        team: 'TEX',
        w: 5,
        l: 3,
        s: 0,
        era: 1.75,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'José',
        lastName: 'Soriano',
        team: 'LAA',
        w: 6,
        l: 5,
        s: 0,
        era: 3.72,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Merill',
        lastName: 'Kelly',
        team: 'AZ',
        w: 7,
        l: 4,
        s: 0,
        era: 3.55,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Nick',
        lastName: 'Pivetta',
        team: 'SD',
        w: 9,
        l: 2,
        s: 0,
        era: 3.25,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Tajiuan',
        lastName: 'Walker',
        team: 'PHI',
        w: 3,
        l: 5,
        s: 0,
        era: 3.64,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Robbie',
        lastName: 'Ray',
        team: 'SF',
        w: 9,
        l: 3,
        s: 0,
        era: 2.68,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Didier',
        lastName: 'Fuentes',
        team: 'ATL',
        w: 0,
        l: 2,
        s: 0,
        era: 9.00,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
    {
        firstName: 'Jeffrey',
        lastName: 'Springs',
        team: 'ATH',
        w: 6,
        l: 6,
        s: 0,
        era: 4.07,
        g: 9,
        gs: 9,
        ip: 44.2,
        h: 42,
        r: 19,
        er: 12,
        hr: 6,
        bb: 14,
        so: 32,
        avg: .251,
        whip: 1.25,
    },
]