module.exports = {
    AZ: {
        name: "Arizona Diamondbacks",
        nickname: ["Diamondbacks", "D-backs", "Snakes"],
        city: "Phoenix",
        state: "Arizona",
        abbreviation: "AZ",
        league: "NL",
        division: "West",
        mlbId: 109,
        logo: "/logos/az-logo.png",
        primaryColor: "#A71930",
        secondaryColor: "#E3D4AD",
        stadium: "Chase Field",
        website: "https://www.dbacks.com",
        network: "ARID",
    },
    ATH: {
        name: "Athletics",
        nickname: ["Athletics", "The A's", "A's", "Swingin' A's", "Amazin' A's"],
        city: "Sacramento (Temporary)",
        state: "California",
        abbreviation: "ATH",
        league: "AL",
        division: "West",
        mlbId: 133,
        logo: "/logos/ath-logo.png",
        primaryColor: "#003831",
        secondaryColor: "#EFB21E",
        stadium: "Sutter Health Park",
        website: "https://www.athletics.com",
        network: "NBCSCA",
    },
    ATL: {
        name: "Atlanta Braves",
        nickname: ["Braves", "Bravos"],
        city: "Atlanta",
        state: "Georgia",
        abbreviation: "ATL",
        league: "NL",
        division: "East",
        mlbId: 144,
        logo: "/logos/atl-logo.png",
        primaryColor: "#CE1141",
        secondaryColor: "#13274F",
        stadium: "Truist Park",
        website: "https://www.braves.com",
        network: "FDSNSO",
    },
    BAL: {
        name: "Baltimore Orioles",
        nickname: ["Orioles", "The O's", "O's", "Birds"],
        city: "Baltimore",
        state: "Maryland",
        abbreviation: "BAL",
        league: "AL",
        division: "East",
        mlbId: 110,
        logo: "/logos/bal-logo.png",
        primaryColor: "#DF4601",
        secondaryColor: "#000000",
        stadium: "Oriole Park at Camden Yards",
        website: "https://www.orioles.com",
        network: "MASN",
    },
    BOS: {
        name: "Boston Red Sox",
        nickname: ["Red Sox", "BoSox", "Sox"],
        city: "Boston",
        state: "Massachusetts",
        abbreviation: "BOS",
        league: "AL",
        division: "East",
        mlbId: 111,
        logo: "/logos/bos-logo.png",
        primaryColor: "#BD3039",
        secondaryColor: "#0C2340",
        stadium: "Fenway Park",
        website: "https://www.redsox.com",
        network: "NESN",
    },
    CHC: {
        name: "Chicago Cubs",
        nickname: ["Cubs", "Cubbies"],
        city: "Chicago",
        state: "Illinois",
        abbreviation: "CHC",
        league: "NL",
        division: "Central",
        mlbId: 112,
        logo: "/logos/chc-logo.png",
        primaryColor: "#0E3386",
        secondaryColor: "#CC3433",
        stadium: "Wrigley Field",
        website: "https://www.cubs.com",
        network: "MARQ",
    },
    CWS: {
        name: "Chicago White Sox",
        nickname: ["White Sox", "Sox", "ChiSox", "South Siders", "South Side Sox"],
        city: "Chicago",
        state: "Illinois",
        abbreviation: "CWS",
        league: "AL",
        division: "Central",
        mlbId: 145,
        logo: "/logos/cws-logo.png",
        primaryColor: "#27251F",
        secondaryColor: "#C4CED4",
        stadium: "Rate Field",
        website: "https://www.whitesox.com",
        network: "CHSN",
    },
    CIN: {
        name: "Cincinnati Reds",
        nickname: ["Reds", "Big Red Machine", "Red Machine"],
        city: "Cincinnati",
        state: "Ohio",
        abbreviation: "CIN",
        league: "NL",
        division: "Central",
        mlbId: 113,
        logo: "/logos/cin-logo.png",
        primaryColor: "#C6011F",
        secondaryColor: "#000000",
        stadium: "Great American Ball Park",
        website: "https://www.reds.com",
        network: "FDSNOH",
    },
    CLE: {
        name: "Cleveland Guardians",
        nickname: ["Guardians", "Guards", "Tribe"],
        city: "Cleveland",
        state: "Ohio",
        abbreviation: "CLE",
        league: "AL",
        division: "Central",
        mlbId: 114,
        logo: "/logos/cle-logo.png",
        primaryColor: "#00385D",
        secondaryColor: "#E50022",
        stadium: "Progressive Field",
        website: "https://www.guardians.com",
        network: "CLEG",
    },
    COL: {
        name: "Colorado Rockies",
        nickname: ["Rockies", "Rocks", "Rox", "Purple Rocks"],
        city: "Denver",
        state: "Colorado",
        abbreviation: "COL",
        league: "NL",
        division: "West",
        mlbId: 115,
        logo: "/logos/col-logo.png",
        primaryColor: "#333366",
        secondaryColor: "#C4CED4",
        stadium: "Coors Field",
        website: "https://www.rockies.com",
        network: "COLR"
    },
    DET: {
        name: "Detroit Tigers",
        nickname: ["Tigers", "Tigres", "Tiges", "Cats"],
        city: "Detroit",
        state: "Michigan",
        abbreviation: "DET",
        league: "AL",
        division: "Central",
        mlbId: 116,
        logo: "/logos/det-logo.png",
        primaryColor: "#0C2340",
        secondaryColor: "#FA4616",
        stadium: "Comerica Park",
        website: "https://www.tigers.com",
        network: "FDSNDT",
    },
    HOU: {
        name: "Houston Astros",
        nickname: ["Astros", "'Stros"],
        city: "Houston",
        state: "Texas",
        abbreviation: "HOU",
        league: "AL",
        division: "West",
        mlbId: 117,
        logo: "/logos/hou-logo.png",
        primaryColor: "#002D62",
        secondaryColor: "#EB6E1F",
        stadium: "Daikin Park",
        website: "https://www.astros.com",
        network: "SCHN",
    },
    KC: {
        name: "Kansas City Royals",
        nickname: ["Royals", "KC Royals"],
        city: "Kansas City",
        state: "Missouri",
        abbreviation: "KC",
        league: "AL",
        division: "Central",
        mlbId: 118,
        logo: "/logos/kc-logo.png",
        primaryColor: "#004687",
        secondaryColor: "#BD9B60",
        stadium: "Kauffman Stadium",
        website: "https://www.royals.com",
        network: "FDSNKC",
    },
    LAA: {
        name: "Los Angeles Angels",
        nickname: ["Angels", "LA Angels", "Los Angeles Angels of Anaheim", "LA Angels of Anaheim", "Halos", "Anaheim Angels"],
        city: "Anaheim",
        state: "California",
        abbreviation: "LAA",
        league: "AL",
        division: "West",
        mlbId: 108,
        logo: "/logos/laa-logo.png",
        primaryColor: "#BA0021",
        secondaryColor: "#C4CED4",
        stadium: "Angel Stadium",
        website: "https://www.angels.com",
        network: "FDSNW",
    },
    LAD: {
        name: "Los Angeles Dodgers",
        nickname: ["Dodgers", "LA Dodgers", "Dodger Blue", "Los Doyers"],
        city: "Los Angeles",
        state: "California",
        abbreviation: "LAD",
        league: "NL",
        division: "West",
        mlbId: 119,
        logo: "/logos/lad-logo.png",
        primaryColor: "#005A9C",
        secondaryColor: "#A5ACAF",
        stadium: "Dodger Stadium",
        website: "https://www.dodgers.com",
        network: "SNLA",
    },
    MIA: {
        name: "Miami Marlins",
        nickname: ["Marlins", "Fish", "Fightin' Fish"],
        city: "Miami",
        state: "Florida",
        abbreviation: "MIA",
        league: "NL",
        division: "East",
        mlbId: 146,
        logo: "/logos/mia-logo.png",
        primaryColor: "#00A3E0",
        secondaryColor: "#41748D",
        stadium: "LoanDepot Park",
        website: "https://www.marlins.com",
        network: "FDSNFL",
    },
    MIL: {
        name: "Milwaukee Brewers",
        nickname: ["Brewers", "Brew Crew", "Crews"],
        city: "Milwaukee",
        state: "Wisconsin",
        abbreviation: "MIL",
        league: "NL",
        division: "Central",
        mlbId: 158,
        logo: "/logos/mil-logo.png",
        primaryColor: "#FFC52F",
        secondaryColor: "#12284B",
        stadium: "American Family Field",
        website: "https://www.brewers.com",
        network: "FDSNWI",
    },
    MIN: {
        name: "Minnesota Twins",
        nickname: ["Twins", "Minneapolis Twins"],
        city: "Minneapolis",
        state: "Minnesota",
        abbreviation: "MIN",
        league: "AL",
        division: "Central",
        mlbId: 142,
        logo: "/logos/min-logo.png",
        primaryColor: "#002B5C",
        secondaryColor: "#D31145",
        stadium: "Target Field",
        website: "https://www.twins.com",
        network: "MNNT",
    },
    NYM: {
        name: "New York Mets",
        nickname: ["Mets", "Metropolitans", "Amazin' Mets", "Amazin's", "Orange and Blue", "NY Mets"],
        city: "Flushing",
        state: "New York",
        abbreviation: "NYM",
        league: "NL",
        division: "East",
        mlbId: 121,
        logo: "/logos/nym-logo.png",
        primaryColor: "#002D72",
        secondaryColor: "#FF5910",
        stadium: "Citi Field",
        website: "https://www.mets.com",
        network: "SNY",
    },
    NYY: {
        name: "New York Yankees",
        nickname: ["Yankees", "Yanks", "Bombers", "Bronx Bombers", "Pinstripes", "NY Yankees"],
        city: "Bronx",
        state: "New York",
        abbreviation: "NYY",
        league: "AL",
        division: "East",
        mlbId: 147,
        logo: "/logos/nyy-logo.png",
        primaryColor: "#0C2340",
        secondaryColor: "#C4CED3",
        stadium: "Yankee Stadium",
        website: "https://www.yankees.com",
        network: "YES",
    },
    PHI: {
        name: "Philadelphia Phillies",
        nickname: ["Phillies", "Phils", "Phightin' Phils", "Phightin Phillies", "Phightin's"],
        city: "Philadelphia",
        state: "Pennsylvania",
        abbreviation: "PHI",
        league: "NL",
        division: "East",
        mlbId: 143,
        logo: "/logos/phi-logo.png",
        primaryColor: "#E81828",
        secondaryColor: "#002D72",
        stadium: "Citizens Bank Park",
        website: "https://www.phillies.com",
        network: "NBCSP",
    },
    PIT: {
        name: "Pittsburgh Pirates",
        nickname: ["Pirates", "Buccos", "Bucs", "Black and Gold"],
        city: "Pittsburgh",
        state: "Pennsylvania",
        abbreviation: "PIT",
        league: "NL",
        division: "Central",
        mlbId: 134,
        logo: "/logos/pit-logo.png",
        primaryColor: "#27251F",
        secondaryColor: "#FDB827",
        stadium: "PNC Park",
        website: "https://www.pirates.com",
        network: "SNP",
    },
    SD: {
        name: "San Diego Padres",
        nickname: ["Padres", "Pads", "Friars"],
        city: "San Diego",
        state: "California",
        abbreviation: "SD",
        league: "NL",
        division: "West",
        mlbId: 135,
        logo: "/logos/sd-logo.png",
        primaryColor: "#2F241D",
        secondaryColor: "#FFC425",
        stadium: "Petco Park",
        website: "https://www.padres.com",
        network: "SDPA",
    },
    SF: {
        name: "San Francisco Giants",
        nickname: ["Giants", "SF Giants", "Jints", "Gints"],
        city: "San Francisco",
        state: "California",
        abbreviation: "SF",
        league: "NL",
        division: "West",
        mlbId: 137,
        logo: "/logos/sf-logo.png",
        primaryColor: "#FD5A1E",
        secondaryColor: "#27251F",
        stadium: "Oracle Park",
        website: "https://www.sfgiants.com",
        network: "NBCSBA",
    },
    SEA: {
        name: "Seattle Mariners",
        nickname: ["Mariners", "M's"],
        city: "Seattle",
        state: "Washington",
        abbreviation: "SEA",
        league: "AL",
        division: "West",
        mlbId: 136,
        logo: "/logos/sea-logo.png",
        primaryColor: "#005C5C",
        secondaryColor: "#C4CED4",
        stadium: "T-Mobile Park",
        website: "https://www.mariners.com",
        network: "RSNW",
    },
    STL: {
        name: "St. Louis Cardinals",
        nickname: ["Cardinals", "Cards", "Redbirds", "Birds"],
        city: "St. Louis",
        state: "Missouri",
        abbreviation: "STL",
        league: "NL",
        division: "Central",
        mlbId: 138,
        logo: "/logos/stl-logo.png",
        primaryColor: "#C41E3A",
        secondaryColor: "#FFFFFF",
        stadium: "Busch Stadium",
        website: "https://www.cardinals.com",
        network: "FDSNMW",
    },
    TB: {
        name: "Tampa Bay Rays",
        nickname: ["Rays", "TB Rays", "Devil Rays", "Tampa Bay Devilrays"],
        city: "Tampa Bay",
        state: "Florida",
        abbreviation: "TB",
        league: "AL",
        division: "East",
        mlbId: 139,
        logo: "/logos/tb-logo.png",
        primaryColor: "#8FBCE6",
        secondaryColor: "#8FBCE6",
        stadium: "Tropicana Field",
        website: "https://www.raysbaseball.com",
        network: "FDSNUN",
    },
    TEX: {
        name: "Texas Rangers",
        nickname: ["Rangers", "Texas Rangers of Arlington", "Arlington Rangers"],
        city: "Arlington",
        state: "Texas",
        abbreviation: "TEX",
        league: "AL",
        division: "West",
        mlbId: 140,
        logo: "/logos/tex-logo.png",
        primaryColor: "#003278",
        secondaryColor: "#C0111F",
        stadium: "Globe Life Field",
        website: "https://www.texasrangers.com",
        network: "RSN",
    },
    TOR: {
        name: "Toronto Blue Jays",
        nickname: ["Blue Jays", "Jays", "Blue Birds", "Birds"],
        city: "Toronto",
        state: "Ontario, Canada",
        abbreviation: "TOR",
        league: "AL",
        division: "East",
        mlbId: 141,
        logo: "/logos/tor-logo.png",
        primaryColor: "#134A8E",
        secondaryColor: "#1D2D5C",
        stadium: "Rogers Centre",
        website: "https://www.bluejays.com",
        network: "Sportsnet",
    },
    WSH: {
        name: "Washington Nationals",
        nickname: ["Nationals", "Nats"],
        city: "Washington, DC",
        abbreviation: "WSH",
        league: "NL",
        division: "East",
        mlbId: 120,
        logo: "/logos/wsh-logo.png",
        primaryColor: "#AB0003",
        secondaryColor: "#14225A",
        stadium: "Nationals Park",
        website: "https://www.nationals.com",
        network: "MASN2"
    },
}